[project]
name = "baixadctf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deep-translator>=1.11.4",
    "dotenv>=0.9.9",
    "pytz>=2025.2",
    "seleniumbase>=4.38.2",
]
